//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUONTRA
    {
        public string MaMuonTra { get; set; }
        public string MaDocGia { get; set; }
        public string MaSach { get; set; }
        public string NguoiChoMuon { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime NgayHenTra { get; set; }
        public string NguoiNhanTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> Phi { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual SACH SACH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
