//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTHUVIEN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUANLYTHUVIENEntities : DbContext
    {
        public QUANLYTHUVIENEntities()
            : base("name=QUANLYTHUVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCGIA> DOCGIAs { get; set; }
        public virtual DbSet<MUONTRA> MUONTRAs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHANLOAI> PHANLOAIs { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<SANGTAC> SANGTACs { get; set; }
        public virtual DbSet<TACGIA> TACGIAs { get; set; }
        public virtual DbSet<THEDOCGIA> THEDOCGIAs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
    
        public virtual ObjectResult<GETAVAILABLEBOOKS_Result> GETAVAILABLEBOOKS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETAVAILABLEBOOKS_Result>("GETAVAILABLEBOOKS");
        }
    
        public virtual ObjectResult<GETAVALIDMEMBER_Result> GETAVALIDMEMBER(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETAVALIDMEMBER_Result>("GETAVALIDMEMBER", nParameter);
        }
    
        public virtual ObjectResult<GETTOPBOOK_Result> GETTOPBOOK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETTOPBOOK_Result>("GETTOPBOOK");
        }
    
        public virtual ObjectResult<GETTOPMEMBER_Result> GETTOPMEMBER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETTOPMEMBER_Result>("GETTOPMEMBER");
        }
    
        public virtual ObjectResult<GETBLACKLIST_Result> GETBLACKLIST(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("N", n) :
                new ObjectParameter("N", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETBLACKLIST_Result>("GETBLACKLIST", nParameter);
        }
    
        public virtual ObjectResult<THEDOCGIALATE_Result> THEDOCGIALATE(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THEDOCGIALATE_Result>("THEDOCGIALATE", nParameter);
        }
    }
}
